export interface MealItem {
  id: string;
  day: number; // 1-based day index
  date: string; // YYYY-MM-DD
  type: 'breakfast' | 'lunch' | 'dinner';
  description: string;
  value: number;
  isAutoGenerated: true;
}

export interface ExpenseItem {
  id: string;
  description: string;
  value: number;
  isAutoGenerated?: boolean;
  mealType?: 'breakfast' | 'lunch' | 'dinner';
  mealDay?: number;
}

export interface TripMemory {
  id: string;
  imageBase64: string;
  caption?: string;
  addedAt: string;
}

export interface AccommodationInfo {
  name: string;
  pricePerNight: number;
  nightsCount: number;
  totalCost: number;
  url?: string;
  photos?: string[]; // base64 strings, max 4
}

export interface TransportCostInfo {
  distanceKm: number; // Distância só de ida (em km)
  isRoundTrip: boolean; // Padrão: true
  fuelPricePerLiter: number; // R$/Litro
  fuelEfficiencyKmL: number; // km/Litro (ex: 10)
  calculatedFuelCost: number; // R$ total de combustível (ida + volta)
  tollCost: number; // R$ estimado de pedágios
}

export interface CarRentalInfo {
  enabled: boolean;
  pricePerDay: number; // Média de mercado (ex: R$ 120,00)
  daysCount: number; // Total de diárias necessárias
  hasSundayExtraDay: boolean; // Se incluiu +1 diária por início ou fim no domingo
  totalCost: number; // pricePerDay * daysCount
}

export interface NearbyPlace {
  id: string;
  name: string;
  category: 'restaurant' | 'cafe' | 'hotel' | 'attraction';
  rating: number;
  distance: string;
  address: string;
  lat: number;
  lng: number;
}

export type TripStatus = 'planned' | 'ongoing' | 'completed';

export interface Trip {
  id: string;
  title: string;
  originAddress: string;
  originLat?: number;
  originLng?: number;
  destinationAddress: string;
  destinationLat?: number;
  destinationLng?: number;
  startDate: string; // ISO string 'YYYY-MM-DD'
  endDate: string;   // ISO string 'YYYY-MM-DD'
  accommodation: AccommodationInfo;
  transport: TransportCostInfo;
  carRental?: CarRentalInfo;
  extraItems: ExpenseItem[];
  breakfastIncluded?: boolean; // Se o café da manhã está incluso na hospedagem
  totalEstimateCost: number;
  notes?: string;
  coverImageUrl?: string;      // URL externa ou base64
  coverImageBase64?: string;   // Upload do usuário (base64)
  memories?: TripMemory[];     // Fotos/lembranças da viagem
  status: TripStatus;
  createdAt: string;
  updatedAt: string;
}

export type TripFormData = Omit<Trip, 'id' | 'createdAt' | 'updatedAt'>;
