export interface ExpenseItem {
  id: string;
  description: string;
  value: number;
  isAutoGenerated?: boolean;
}

export interface AccommodationInfo {
  name: string;
  pricePerNight: number;
  nightsCount: number;
  totalCost: number;
}

export interface TransportCostInfo {
  distanceKm: number; // Distância só de ida (em km)
  isRoundTrip: boolean; // Padrão: true
  fuelPricePerLiter: number; // R$/Litro
  fuelEfficiencyKmL: number; // km/Litro (ex: 10)
  calculatedFuelCost: number; // R$ total de combustível
  tollCost: number; // R$ estimado de pedágios
}

export interface CarRentalInfo {
  enabled: boolean;
  pricePerDay: number; // Média de mercado (ex: R$ 120,00)
  daysCount: number; // Total de diárias necessárias
  hasSundayExtraDay: boolean; // Se incluiu +1 diária por início ou fim no domingo
  totalCost: number; // pricePerDay * daysCount
}

export interface NearbyPlace {
  id: string;
  name: string;
  category: 'restaurant' | 'cafe' | 'hotel' | 'attraction';
  rating: number;
  distance: string;
  address: string;
  lat: number;
  lng: number;
}

export type TripStatus = 'planned' | 'ongoing' | 'completed';

export interface Trip {
  id: string;
  title: string;
  originAddress: string;
  destinationAddress: string;
  destinationLat?: number;
  destinationLng?: number;
  startDate: string; // ISO string 'YYYY-MM-DD'
  endDate: string;   // ISO string 'YYYY-MM-DD'
  accommodation: AccommodationInfo;
  transport: TransportCostInfo;
  carRental?: CarRentalInfo;
  extraItems: ExpenseItem[];
  totalEstimateCost: number; // Soma de Hospedagem + Aluguel Carro + Combustível + Pedágios + Itens Extras
  notes?: string;
  coverImageUrl?: string;
  status: TripStatus;
  createdAt: string;
  updatedAt: string;
}

export type TripFormData = Omit<Trip, 'id' | 'createdAt' | 'updatedAt'>;
