import React, { useState, useEffect } from 'react';
import { X, MapPin, Calendar, Hotel, Fuel, Ticket, Plus, Trash2, Calculator, Sparkles, Navigation, RotateCcw, Info, Car, AlertCircle } from 'lucide-react';
import type { Trip, TripFormData, ExpenseItem, CarRentalInfo } from '../types/trip';
import {
  DEFAULT_ORIGIN_ADDRESS,
  calculateRouteDetails,
  estimateTollCost,
  calculateFuelCost,
  calculateCarRentalDays,
  DEFAULT_CAR_RENTAL_DAILY_PRICE,
  searchDestinationAutocomplete,
  type PlaceAutocompleteOption
} from '../services/routeService';
import { formatCurrency, calculateNights } from '../utils/formatters';
import { MapRoute } from './MapRoute';

interface TripFormModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (tripData: TripFormData, editTripId?: string) => Promise<void>;
  tripToEdit?: Trip | null;
}

export const TripFormModal: React.FC<TripFormModalProps> = ({
  isOpen,
  onClose,
  onSave,
  tripToEdit
}) => {
  const [title, setTitle] = useState('');
  const [originAddress, setOriginAddress] = useState(DEFAULT_ORIGIN_ADDRESS);
  const [destinationAddress, setDestinationAddress] = useState('');
  const [destLat, setDestLat] = useState<number>(-27.5954);
  const [destLng, setDestLng] = useState<number>(-48.5480);
  
  // Autocomplete
  const [autocompleteSuggestions, setAutocompleteSuggestions] = useState<PlaceAutocompleteOption[]>([]);
  const [showAutocomplete, setShowAutocomplete] = useState(false);

  // Datas
  const todayStr = new Date().toISOString().split('T')[0];
  const nextWeekStr = new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];
  const [startDate, setStartDate] = useState(todayStr);
  const [endDate, setEndDate] = useState(nextWeekStr);

  // Hospedagem
  const [accommodationName, setAccommodationName] = useState('');
  const [pricePerNight, setPricePerNight] = useState<number>(150);

  // Transporte & Combustível
  const [distanceKm, setDistanceKm] = useState<number>(300);
  const [fuelPricePerLiter, setFuelPricePerLiter] = useState<number>(5.89);
  const [fuelEfficiencyKmL, setFuelEfficiencyKmL] = useState<number>(10);
  const [isRoundTrip] = useState<boolean>(true);
  const [tollCost, setTollCost] = useState<number>(45);

  // Aluguel de Carro
  const [carRentalEnabled, setCarRentalEnabled] = useState<boolean>(false);
  const [carRentalPricePerDay, setCarRentalPricePerDay] = useState<number>(DEFAULT_CAR_RENTAL_DAILY_PRICE);
  const [carRentalDaysCount, setCarRentalDaysCount] = useState<number>(5);
  const [hasSundayExtraDay, setHasSundayExtraDay] = useState<boolean>(false);

  // Itens Extras
  const [extraItems, setExtraItems] = useState<ExpenseItem[]>([]);
  const [newItemDesc, setNewItemDesc] = useState('');
  const [newItemValue, setNewItemValue] = useState<string>('');

  // UI States
  const [isCalculatingRoute, setIsCalculatingRoute] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [notes, setNotes] = useState('');

  // Atualiza regras de carro e alimentação automática quando as datas mudam
  useEffect(() => {
    const nights = calculateNights(startDate, endDate);
    const { daysCount, hasSundayExtraDay } = calculateCarRentalDays(startDate, endDate);

    setCarRentalDaysCount(daysCount);
    setHasSundayExtraDay(hasSundayExtraDay);

    // Atualiza ou cria item automático de Alimentação em Restaurantes (R$ 150/dia)
    const foodCost = nights * 150;
    setExtraItems(prevItems => {
      const existingFoodIndex = prevItems.findIndex(i => i.isAutoGenerated || i.description.toLowerCase().includes('alimentação'));
      const foodItem: ExpenseItem = {
        id: existingFoodIndex >= 0 ? prevItems[existingFoodIndex].id : `food_auto_${Date.now()}`,
        description: `Alimentação em restaurantes (${nights} dias)`,
        value: foodCost,
        isAutoGenerated: true
      };

      if (existingFoodIndex >= 0) {
        const updated = [...prevItems];
        updated[existingFoodIndex] = foodItem;
        return updated;
      } else {
        return [foodItem, ...prevItems];
      }
    });
  }, [startDate, endDate]);

  // Carrega dados se for edição
  useEffect(() => {
    if (tripToEdit) {
      setTitle(tripToEdit.title || '');
      setOriginAddress(tripToEdit.originAddress || DEFAULT_ORIGIN_ADDRESS);
      setDestinationAddress(tripToEdit.destinationAddress || '');
      setDestLat(tripToEdit.destinationLat || -27.5954);
      setDestLng(tripToEdit.destinationLng || -48.5480);

      setStartDate(tripToEdit.startDate || todayStr);
      setEndDate(tripToEdit.endDate || nextWeekStr);
      
      setAccommodationName(tripToEdit.accommodation?.name || '');
      setPricePerNight(tripToEdit.accommodation?.pricePerNight || 0);

      setDistanceKm(tripToEdit.transport?.distanceKm || 0);
      setFuelPricePerLiter(tripToEdit.transport?.fuelPricePerLiter || 5.89);
      setFuelEfficiencyKmL(tripToEdit.transport?.fuelEfficiencyKmL || 10);
      setTollCost(tripToEdit.transport?.tollCost || 0);

      if (tripToEdit.carRental) {
        setCarRentalEnabled(tripToEdit.carRental.enabled);
        setCarRentalPricePerDay(tripToEdit.carRental.pricePerDay || DEFAULT_CAR_RENTAL_DAILY_PRICE);
        setCarRentalDaysCount(tripToEdit.carRental.daysCount || 5);
        setHasSundayExtraDay(tripToEdit.carRental.hasSundayExtraDay || false);
      }

      setExtraItems(tripToEdit.extraItems || []);
      setNotes(tripToEdit.notes || '');
    } else if (isOpen) {
      resetForm();
    }
  }, [tripToEdit, isOpen]);

  const resetForm = () => {
    setTitle('');
    setOriginAddress(DEFAULT_ORIGIN_ADDRESS);
    setDestinationAddress('');
    setDestLat(-27.5954);
    setDestLng(-48.5480);
    setStartDate(todayStr);
    setEndDate(nextWeekStr);
    setAccommodationName('');
    setPricePerNight(150);
    setDistanceKm(300);
    setFuelPricePerLiter(5.89);
    setFuelEfficiencyKmL(10);
    setTollCost(45);
    setCarRentalEnabled(false);
    setCarRentalPricePerDay(DEFAULT_CAR_RENTAL_DAILY_PRICE);

    const nights = calculateNights(todayStr, nextWeekStr);
    setExtraItems([
      { id: `food_auto_${Date.now()}`, description: `Alimentação em restaurantes (${nights} dias)`, value: nights * 150, isAutoGenerated: true }
    ]);
    setNotes('');
  };

  // Autocompletar Destino ao Digitar
  const handleDestinationChange = async (value: string) => {
    setDestinationAddress(value);
    if (value.trim().length >= 2) {
      const suggestions = await searchDestinationAutocomplete(value);
      setAutocompleteSuggestions(suggestions);
      setShowAutocomplete(true);
    } else {
      setShowAutocomplete(false);
    }
  };

  // Selecionar sugestão de autocompletar
  const handleSelectAutocomplete = (option: PlaceAutocompleteOption) => {
    setDestinationAddress(option.display_name);
    setDestLat(option.lat);
    setDestLng(option.lng);
    setShowAutocomplete(false);
    handleAutoCalculateRoute(option.display_name);
  };

  // Cálculo automático de rota
  const handleAutoCalculateRoute = async (destQuery?: string) => {
    const query = destQuery !== undefined ? destQuery : destinationAddress;
    if (!query.trim()) return;

    setIsCalculatingRoute(true);
    try {
      const routeInfo = await calculateRouteDetails(
        query,
        fuelPricePerLiter,
        fuelEfficiencyKmL,
        isRoundTrip
      );

      setDistanceKm(routeInfo.distanceKm);
      setTollCost(routeInfo.estimatedTollCost);
      setDestLat(routeInfo.destLat);
      setDestLng(routeInfo.destLng);

      if (!title) {
        setTitle(`Viagem para ${query.split(',')[0]}`);
      }
    } finally {
      setIsCalculatingRoute(false);
    }
  };

  // Cálculos dinâmicos
  const nights = calculateNights(startDate, endDate);
  const totalAccommodationCost = Math.round((nights * (pricePerNight || 0)) * 100) / 100;
  const calculatedFuelCost = calculateFuelCost(distanceKm, fuelPricePerLiter, fuelEfficiencyKmL, isRoundTrip);
  const totalCarRentalCost = carRentalEnabled ? (carRentalDaysCount * carRentalPricePerDay) : 0;
  const totalExtraItemsCost = extraItems.reduce((sum, item) => sum + (item.value || 0), 0);
  const totalEstimateCost = Math.round((totalAccommodationCost + totalCarRentalCost + calculatedFuelCost + (tollCost || 0) + totalExtraItemsCost) * 100) / 100;

  // Adicionar item extra
  const handleAddExtraItem = () => {
    if (!newItemDesc.trim()) return;
    const val = parseFloat(newItemValue.replace(',', '.')) || 0;
    
    const newItem: ExpenseItem = {
      id: `item_${Date.now()}`,
      description: newItemDesc.trim(),
      value: val
    };

    setExtraItems([...extraItems, newItem]);
    setNewItemDesc('');
    setNewItemValue('');
  };

  // Remover item extra
  const handleRemoveExtraItem = (id: string) => {
    setExtraItems(extraItems.filter(item => item.id !== id));
  };

  // Submissão do Formulário
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!destinationAddress.trim()) {
      alert('Por favor, informe o local de destino!');
      return;
    }

    setIsSaving(true);
    try {
      const carRentalInfo: CarRentalInfo = {
        enabled: carRentalEnabled,
        pricePerDay: carRentalPricePerDay,
        daysCount: carRentalDaysCount,
        hasSundayExtraDay,
        totalCost: totalCarRentalCost
      };

      const formData: TripFormData = {
        title: title.trim() || `Viagem para ${destinationAddress}`,
        originAddress: originAddress || DEFAULT_ORIGIN_ADDRESS,
        destinationAddress,
        destinationLat: destLat,
        destinationLng: destLng,
        startDate,
        endDate,
        accommodation: {
          name: accommodationName || 'Hospedagem',
          pricePerNight: pricePerNight || 0,
          nightsCount: nights,
          totalCost: totalAccommodationCost
        },
        transport: {
          distanceKm: distanceKm || 0,
          isRoundTrip,
          fuelPricePerLiter: fuelPricePerLiter || 0,
          fuelEfficiencyKmL: fuelEfficiencyKmL || 10,
          calculatedFuelCost,
          tollCost: tollCost || 0
        },
        carRental: carRentalInfo,
        extraItems,
        notes,
        totalEstimateCost,
        status: 'planned'
      };

      await onSave(formData, tripToEdit ? tripToEdit.id : undefined);
      onClose();
    } catch (err) {
      console.error("Erro ao salvar viagem:", err);
      alert("Erro ao salvar viagem no banco de dados. Verifique a conexão.");
    } finally {
      setIsSaving(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 overflow-y-auto bg-slate-950/80 backdrop-blur-md">
      <div className="relative w-full max-w-4xl bg-slate-900 border border-slate-800 rounded-3xl shadow-2xl overflow-hidden my-8">
        
        {/* Cabeçalho do Modal */}
        <div className="flex items-center justify-between p-6 border-b border-slate-800 bg-slate-950/60">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 bg-gradient-to-br from-cyan-500 to-blue-600 rounded-2xl text-white shadow-lg shadow-cyan-500/20">
              <Sparkles className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white">
                {tripToEdit ? 'Editar Viagem' : 'Nova Viagem'}
              </h2>
              <p className="text-xs text-slate-400">Preencha os dados e estimativas de gastos da sua rota</p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 text-slate-400 hover:text-white rounded-xl bg-slate-800/80 hover:bg-slate-800 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Corpo do Formulário */}
        <form onSubmit={handleSubmit} className="p-6 space-y-6 max-h-[78vh] overflow-y-auto custom-scrollbar">
          
          {/* Título da Viagem */}
          <div>
            <label className="block text-xs font-semibold text-slate-300 uppercase tracking-wider mb-2">
              Título da Viagem (Opcional)
            </label>
            <input
              type="text"
              placeholder="Ex: Férias em Florianópolis"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 focus:border-cyan-500 rounded-xl px-4 py-3 text-sm text-slate-100 placeholder-slate-500 outline-none transition-colors"
            />
          </div>

          {/* Origem e Destino com Autopreenchimento (Autocomplete) */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 bg-slate-950/60 p-4 rounded-2xl border border-slate-800">
            
            {/* Endereço de Partida Fixado */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="text-xs font-semibold text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
                  <Navigation className="w-3.5 h-3.5 text-cyan-400" /> Local de Partida (Fixo)
                </label>
                <button
                  type="button"
                  onClick={() => setOriginAddress(DEFAULT_ORIGIN_ADDRESS)}
                  title="Restaurar endereço padrão"
                  className="text-[10px] text-cyan-400 hover:underline flex items-center gap-1 cursor-pointer"
                >
                  <RotateCcw className="w-3 h-3" /> Restaurar
                </button>
              </div>
              <input
                type="text"
                value={originAddress}
                onChange={(e) => setOriginAddress(e.target.value)}
                className="w-full bg-slate-900 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-slate-300 outline-none"
              />
              <p className="text-[10px] text-slate-400 mt-1 flex items-center gap-1">
                <Info className="w-3 h-3 text-cyan-400" /> Endereço fixado em Ribeirão Preto - SP
              </p>
            </div>

            {/* Local de Destino com Autocompletar */}
            <div className="relative">
              <label className="block text-xs font-semibold text-slate-300 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                <MapPin className="w-3.5 h-3.5 text-rose-400" /> Local de Destino
              </label>
              <div className="relative">
                <input
                  type="text"
                  placeholder="Digite para buscar a cidade ou destino..."
                  value={destinationAddress}
                  onChange={(e) => handleDestinationChange(e.target.value)}
                  onFocus={() => destinationAddress.length >= 2 && setShowAutocomplete(true)}
                  className="w-full bg-slate-950 border border-slate-800 focus:border-cyan-500 rounded-xl px-4 py-2.5 text-sm text-slate-100 placeholder-slate-500 outline-none transition-colors"
                  required
                />
                <button
                  type="button"
                  onClick={() => handleAutoCalculateRoute()}
                  disabled={isCalculatingRoute}
                  className="absolute right-2 top-1/2 -translate-y-1/2 px-3 py-1 bg-cyan-950 text-cyan-400 border border-cyan-800 rounded-lg text-xs font-semibold hover:bg-cyan-900 transition-colors flex items-center gap-1 cursor-pointer"
                >
                  {isCalculatingRoute ? (
                    <span className="animate-spin text-xs">🌀</span>
                  ) : (
                    <Calculator className="w-3.5 h-3.5" />
                  )}
                  <span>Calcular</span>
                </button>
              </div>

              {/* Lista de Sugestões de Autocompletar */}
              {showAutocomplete && autocompleteSuggestions.length > 0 && (
                <div className="absolute left-0 right-0 top-full mt-1 bg-slate-900 border border-slate-700 rounded-xl shadow-2xl z-50 max-h-48 overflow-y-auto">
                  {autocompleteSuggestions.map((item, idx) => (
                    <button
                      key={idx}
                      type="button"
                      onClick={() => handleSelectAutocomplete(item)}
                      className="w-full text-left px-4 py-2.5 text-xs text-slate-200 hover:bg-slate-800 flex items-center gap-2 border-b border-slate-800/50 last:border-0"
                    >
                      <MapPin className="w-3.5 h-3.5 text-cyan-400 shrink-0" />
                      <span>{item.display_name}</span>
                    </button>
                  ))}
                </div>
              )}
            </div>

          </div>

          {/* Mapa Interativo com Trajeto & Recomendações */}
          {destinationAddress.trim().length > 0 && (
            <MapRoute
              destinationName={destinationAddress}
              destLat={destLat}
              destLng={destLng}
            />
          )}

          {/* Datas de Ida e Volta */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 bg-slate-950/60 p-4 rounded-2xl border border-slate-800">
            <div>
              <label className="block text-xs font-semibold text-slate-300 uppercase tracking-wider mb-2 flex items-center gap-1">
                <Calendar className="w-3.5 h-3.5 text-cyan-400" /> Data de Ida
              </label>
              <input
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                className="w-full bg-slate-900 border border-slate-800 rounded-xl px-3 py-2 text-sm text-slate-100 outline-none"
                required
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-300 uppercase tracking-wider mb-2 flex items-center gap-1">
                <Calendar className="w-3.5 h-3.5 text-cyan-400" /> Data de Volta
              </label>
              <input
                type="date"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                className="w-full bg-slate-900 border border-slate-800 rounded-xl px-3 py-2 text-sm text-slate-100 outline-none"
                required
              />
            </div>

            <div className="flex flex-col justify-center items-center bg-slate-900/80 rounded-xl p-3 border border-slate-800">
              <span className="text-[10px] text-slate-400 uppercase font-semibold">Total de Noites</span>
              <span className="text-xl font-extrabold text-cyan-400">{nights} {nights === 1 ? 'Noite' : 'Noites'}</span>
            </div>
          </div>

          {/* Hospedagem */}
          <div className="bg-slate-950/60 p-4 rounded-2xl border border-slate-800 space-y-4">
            <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider flex items-center gap-2">
              <Hotel className="w-4 h-4 text-indigo-400" /> Hospedagem
            </h4>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div className="sm:col-span-2">
                <label className="block text-xs text-slate-400 mb-1">Local de Hospedagem</label>
                <input
                  type="text"
                  placeholder="Ex: Pousada Beira Mar ou Airbnb"
                  value={accommodationName}
                  onChange={(e) => setAccommodationName(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-800 rounded-xl px-3.5 py-2 text-sm text-slate-100 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs text-slate-400 mb-1">Preço por Diária (R$)</label>
                <input
                  type="number"
                  step="0.01"
                  min="0"
                  value={pricePerNight}
                  onChange={(e) => setPricePerNight(parseFloat(e.target.value) || 0)}
                  className="w-full bg-slate-900 border border-slate-800 rounded-xl px-3.5 py-2 text-sm text-slate-100 outline-none"
                />
              </div>
            </div>

            <div className="flex justify-between items-center text-xs text-slate-400 bg-slate-900 p-2.5 rounded-xl border border-slate-800">
              <span>Custo Total de Hospedagem ({nights}x {formatCurrency(pricePerNight)}):</span>
              <span className="font-bold text-indigo-400 text-sm">{formatCurrency(totalAccommodationCost)}</span>
            </div>
          </div>

          {/* Transporte, Combustível & Pedágios */}
          <div className="bg-slate-950/60 p-4 rounded-2xl border border-slate-800 space-y-4">
            <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider flex items-center gap-2">
              <Fuel className="w-4 h-4 text-amber-400" /> Transporte, Combustível & Pedágios
            </h4>

            <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 text-xs">
              <div>
                <label className="block text-slate-400 mb-1">Distância (Ida em Km)</label>
                <input
                  type="number"
                  min="1"
                  value={distanceKm}
                  onChange={(e) => {
                    const dist = parseFloat(e.target.value) || 0;
                    setDistanceKm(dist);
                    setTollCost(estimateTollCost(dist, isRoundTrip));
                  }}
                  className="w-full bg-slate-900 border border-slate-800 rounded-xl px-3 py-2 text-slate-100 outline-none font-semibold"
                />
              </div>

              <div>
                <label className="block text-slate-400 mb-1">Preço Combustível (R$/L)</label>
                <input
                  type="number"
                  step="0.01"
                  min="0"
                  value={fuelPricePerLiter}
                  onChange={(e) => setFuelPricePerLiter(parseFloat(e.target.value) || 0)}
                  className="w-full bg-slate-900 border border-slate-800 rounded-xl px-3 py-2 text-slate-100 outline-none"
                />
              </div>

              <div>
                <label className="block text-slate-400 mb-1">Consumo do Carro (km/L)</label>
                <input
                  type="number"
                  step="0.1"
                  min="1"
                  value={fuelEfficiencyKmL}
                  onChange={(e) => setFuelEfficiencyKmL(parseFloat(e.target.value) || 10)}
                  className="w-full bg-slate-900 border border-slate-800 rounded-xl px-3 py-2 text-slate-100 outline-none"
                />
              </div>

              <div>
                <label className="block text-slate-400 mb-1">Estimativa Pedágios (R$)</label>
                <input
                  type="number"
                  step="0.01"
                  min="0"
                  value={tollCost}
                  onChange={(e) => setTollCost(parseFloat(e.target.value) || 0)}
                  className="w-full bg-slate-900 border border-slate-800 rounded-xl px-3 py-2 text-slate-100 outline-none"
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3 text-xs bg-slate-900 p-2.5 rounded-xl border border-slate-800">
              <div className="flex items-center justify-between">
                <span className="text-slate-400">Total Combustível (Ida e Volta):</span>
                <span className="font-bold text-amber-400">{formatCurrency(calculatedFuelCost)}</span>
              </div>
              <div className="flex items-center justify-between border-l border-slate-800 pl-3">
                <span className="text-slate-400">Total Pedágios:</span>
                <span className="font-bold text-cyan-400">{formatCurrency(tollCost)}</span>
              </div>
            </div>
          </div>

          {/* ABA DE ALUGUEL DE CARRO (COMPLEMENTO DE TRANSPORTE) */}
          <div className="bg-slate-950/60 p-4 rounded-2xl border border-slate-800 space-y-4">
            <div className="flex items-center justify-between">
              <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider flex items-center gap-2">
                <Car className="w-4 h-4 text-blue-400" /> Aluguel de Veículo (Locação)
              </h4>

              {/* Seletor Sim / Não */}
              <div className="flex items-center gap-2 bg-slate-900 p-1 rounded-xl border border-slate-800">
                <button
                  type="button"
                  onClick={() => setCarRentalEnabled(true)}
                  className={`px-3 py-1 rounded-lg text-xs font-semibold transition-colors cursor-pointer ${
                    carRentalEnabled ? 'bg-blue-600 text-white' : 'text-slate-400 hover:text-slate-200'
                  }`}
                >
                  Sim
                </button>
                <button
                  type="button"
                  onClick={() => setCarRentalEnabled(false)}
                  className={`px-3 py-1 rounded-lg text-xs font-semibold transition-colors cursor-pointer ${
                    !carRentalEnabled ? 'bg-slate-800 text-slate-300' : 'text-slate-400 hover:text-slate-200'
                  }`}
                >
                  Não
                </button>
              </div>
            </div>

            {/* Estende as opções se Sim for selecionado */}
            {carRentalEnabled && (
              <div className="p-4 bg-slate-900 rounded-2xl border border-blue-800/60 space-y-4 animate-fadeIn">
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs">
                  <div>
                    <label className="block text-slate-400 mb-1">Preço da Diária do Carro (R$)</label>
                    <input
                      type="number"
                      step="0.01"
                      min="0"
                      value={carRentalPricePerDay}
                      onChange={(e) => setCarRentalPricePerDay(parseFloat(e.target.value) || 0)}
                      className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-slate-100 outline-none font-semibold"
                    />
                    <span className="text-[10px] text-slate-500 mt-1 block">Média de mercado: R$ 120,00</span>
                  </div>

                  <div>
                    <label className="block text-slate-400 mb-1">Quantidade de Diárias</label>
                    <input
                      type="number"
                      min="1"
                      value={carRentalDaysCount}
                      onChange={(e) => setCarRentalDaysCount(parseInt(e.target.value) || 1)}
                      className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-slate-100 outline-none font-semibold"
                    />
                  </div>

                  <div className="flex flex-col justify-center bg-slate-950 p-3 rounded-xl border border-slate-800">
                    <span className="text-[10px] text-slate-400 uppercase font-semibold">Total Aluguel Carro</span>
                    <span className="text-lg font-extrabold text-blue-400">{formatCurrency(totalCarRentalCost)}</span>
                  </div>
                </div>

                {/* Regra do Domingo */}
                {hasSundayExtraDay && (
                  <div className="p-2.5 bg-blue-950/60 rounded-xl border border-blue-800/80 text-[11px] text-blue-300 flex items-center gap-2">
                    <AlertCircle className="w-4 h-4 text-blue-400 shrink-0" />
                    <span>
                      <strong>Regra do Domingo ativa:</strong> Como a viagem inicia ou termina no domingo, +1 diária de locação foi adicionada automaticamente.
                    </span>
                  </div>
                )}
              </div>
            )}
          </div>

          {/* Itens Extras & Alimentação */}
          <div className="bg-slate-950/60 p-4 rounded-2xl border border-slate-800 space-y-4">
            <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider flex items-center gap-2">
              <Ticket className="w-4 h-4 text-emerald-400" /> Itens Extras & Alimentação em Restaurantes
            </h4>

            {/* Inputs para adicionar novo item */}
            <div className="flex flex-col sm:flex-row gap-2">
              <input
                type="text"
                placeholder="Descrição do item (ex: Ingressos, Passeios)"
                value={newItemDesc}
                onChange={(e) => setNewItemDesc(e.target.value)}
                className="flex-1 bg-slate-900 border border-slate-800 rounded-xl px-3.5 py-2 text-xs text-slate-100 outline-none"
              />
              <input
                type="number"
                step="0.01"
                placeholder="Valor R$"
                value={newItemValue}
                onChange={(e) => setNewItemValue(e.target.value)}
                className="w-full sm:w-36 bg-slate-900 border border-slate-800 rounded-xl px-3.5 py-2 text-xs text-slate-100 outline-none"
              />
              <button
                type="button"
                onClick={handleAddExtraItem}
                className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white font-semibold rounded-xl text-xs flex items-center justify-center gap-1 transition-colors cursor-pointer"
              >
                <Plus className="w-4 h-4" /> Adicionar
              </button>
            </div>

            {/* Lista de itens extras cadastrados */}
            {extraItems.length > 0 ? (
              <div className="space-y-1.5 max-h-40 overflow-y-auto pr-1">
                {extraItems.map((item) => (
                  <div key={item.id} className="flex items-center justify-between p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-xs">
                    <span className="text-slate-200 font-medium">{item.description}</span>
                    <div className="flex items-center gap-3">
                      <span className="font-semibold text-emerald-400">{formatCurrency(item.value)}</span>
                      <button
                        type="button"
                        onClick={() => handleRemoveExtraItem(item.id)}
                        className="text-slate-500 hover:text-rose-400 transition-colors cursor-pointer"
                        title="Excluir item"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-xs text-slate-500 italic">Nenhum item extra cadastrado.</p>
            )}
          </div>

          {/* Resumo Final e Estimativa Geral */}
          <div className="p-4 bg-gradient-to-r from-slate-950 via-slate-900 to-slate-950 rounded-2xl border border-cyan-500/30 flex flex-col sm:flex-row items-center justify-between gap-4">
            <div>
              <span className="text-xs uppercase font-semibold text-slate-400 block">Estimativa Total de Gastos da Viagem</span>
              <span className="text-2xl font-black text-emerald-400">{formatCurrency(totalEstimateCost)}</span>
            </div>

            <div className="flex items-center gap-3 w-full sm:w-auto">
              <button
                type="button"
                onClick={onClose}
                className="flex-1 sm:flex-none px-4 py-2.5 rounded-xl text-xs font-semibold text-slate-300 bg-slate-800 hover:bg-slate-700 transition-colors cursor-pointer"
              >
                Cancelar
              </button>
              
              <button
                type="submit"
                disabled={isSaving}
                className="flex-1 sm:flex-none px-6 py-2.5 rounded-xl text-xs font-bold text-white bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 shadow-lg shadow-cyan-500/25 transition-all flex items-center justify-center gap-2 cursor-pointer"
              >
                {isSaving ? 'Salvando...' : tripToEdit ? 'Salvar Alterações' : 'Criar Viagem'}
              </button>
            </div>
          </div>

        </form>

      </div>
    </div>
  );
};
