import React, { useState, useEffect, useRef } from 'react';
import {
  X, MapPin, Calendar, Hotel, Fuel, Ticket, Plus, Trash2, Calculator,
  Sparkles, Navigation, RotateCcw, Info, Car, AlertCircle, Image, Link,
  Coffee, Upload, Route, HelpCircle
} from 'lucide-react';
import type { Trip, TripFormData, ExpenseItem, CarRentalInfo } from '../types/trip';
import {
  DEFAULT_ORIGIN_ADDRESS,
  DEFAULT_ORIGIN_COORDS,
  calculateRouteDetails,
  estimateTollCost,
  calculateFuelCost,
  calculateCarRentalDays,
  DEFAULT_CAR_RENTAL_DAILY_PRICE,
  searchPlaceAutocomplete,
  type PlaceAutocompleteOption
} from '../services/routeService';
import { formatCurrency, calculateNights } from '../utils/formatters';
import { MapRoute } from './MapRoute';

interface TripFormModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (tripData: TripFormData, editTripId?: string) => Promise<void>;
  tripToEdit?: Trip | null;
}

// Helper: comprime imagem para base64
async function compressImageToBase64(file: File, maxPx = 800): Promise<string> {
  return new Promise((resolve) => {
    const img = new window.Image();
    const url = URL.createObjectURL(file);
    img.onload = () => {
      const canvas = document.createElement('canvas');
      let { width, height } = img;
      if (width > maxPx || height > maxPx) {
        if (width > height) { height = Math.round((height / width) * maxPx); width = maxPx; }
        else { width = Math.round((width / height) * maxPx); height = maxPx; }
      }
      canvas.width = width;
      canvas.height = height;
      canvas.getContext('2d')!.drawImage(img, 0, 0, width, height);
      URL.revokeObjectURL(url);
      resolve(canvas.toDataURL('image/jpeg', 0.82));
    };
    img.src = url;
  });
}

// Gera itens automáticos de alimentação por dia
function generateMealItems(startDate: string, endDate: string, breakfastIncluded: boolean): ExpenseItem[] {
  if (!startDate || !endDate) return [];
  const [sy, sm, sd] = startDate.split('-').map(Number);
  const [ey, em, ed] = endDate.split('-').map(Number);
  const start = new Date(sy, sm - 1, sd);
  const end = new Date(ey, em - 1, ed);
  const nights = Math.max(1, Math.ceil((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24)));
  
  const items: ExpenseItem[] = [];
  for (let i = 0; i < nights; i++) {
    const d = new Date(start);
    d.setDate(d.getDate() + i);
    const dateStr = d.toISOString().split('T')[0];
    const dayNum = i + 1;
    const label = `${d.toLocaleDateString('pt-BR', { weekday: 'short', day: '2-digit', month: '2-digit' })}`;

    if (!breakfastIncluded) {
      items.push({
        id: `meal_bf_${dateStr}`,
        description: `☕ Café da Manhã — Dia ${dayNum} (${label})`,
        value: 15,
        isAutoGenerated: true,
        mealType: 'breakfast',
        mealDay: dayNum
      });
    }
    items.push({
      id: `meal_ln_${dateStr}`,
      description: `🍽️ Almoço — Dia ${dayNum} (${label})`,
      value: 100,
      isAutoGenerated: true,
      mealType: 'lunch',
      mealDay: dayNum
    });
    items.push({
      id: `meal_dn_${dateStr}`,
      description: `🌙 Jantar — Dia ${dayNum} (${label})`,
      value: 200,
      isAutoGenerated: true,
      mealType: 'dinner',
      mealDay: dayNum
    });
  }
  return items;
}

export const TripFormModal: React.FC<TripFormModalProps> = ({
  isOpen, onClose, onSave, tripToEdit
}) => {
  const todayStr = new Date().toISOString().split('T')[0];
  const nextWeekStr = new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];

  // Básico
  const [title, setTitle] = useState('');
  
  // Partida (Origin)
  const [originAddress, setOriginAddress] = useState(DEFAULT_ORIGIN_ADDRESS);
  const [originLat, setOriginLat] = useState<number>(DEFAULT_ORIGIN_COORDS.lat);
  const [originLng, setOriginLng] = useState<number>(DEFAULT_ORIGIN_COORDS.lng);
  const [originSuggestions, setOriginSuggestions] = useState<PlaceAutocompleteOption[]>([]);
  const [showOriginAutocomplete, setShowOriginAutocomplete] = useState(false);
  const originRef = useRef<HTMLDivElement>(null);
  const originTimerRef = useRef<any>(null);

  // Destino (Destination)
  const [destinationAddress, setDestinationAddress] = useState('');
  const [destLat, setDestLat] = useState<number>(-27.5954);
  const [destLng, setDestLng] = useState<number>(-48.5480);
  const [destSuggestions, setDestSuggestions] = useState<PlaceAutocompleteOption[]>([]);
  const [showDestAutocomplete, setShowDestAutocomplete] = useState(false);
  const destRef = useRef<HTMLDivElement>(null);
  const destTimerRef = useRef<any>(null);

  const [routePolyline, setRoutePolyline] = useState<[number, number][] | undefined>();

  // Datas
  const [startDate, setStartDate] = useState(todayStr);
  const [endDate, setEndDate] = useState(nextWeekStr);

  // Hospedagem
  const [accommodationName, setAccommodationName] = useState('');
  const [pricePerNight, setPricePerNight] = useState<number>(150);
  const [accommodationUrl, setAccommodationUrl] = useState('');
  const [accommodationPhotos, setAccommodationPhotos] = useState<string[]>([]);
  const [previewPhotoUrl, setPreviewPhotoUrl] = useState<string | null>(null);

  // Imagem de Capa
  const [coverImageBase64, setCoverImageBase64] = useState<string>('');
  const coverInputRef = useRef<HTMLInputElement>(null);
  const accomPhotosInputRef = useRef<HTMLInputElement>(null);

  // Suporte a comando voltar no mobile para o lightbox de fotos da hospedagem no formulário
  useEffect(() => {
    if (!previewPhotoUrl) return;

    window.history.pushState({ previewPhotoOpen: true }, '');

    const handlePopState = () => {
      setPreviewPhotoUrl(null);
    };

    window.addEventListener('popstate', handlePopState);

    return () => {
      window.removeEventListener('popstate', handlePopState);
    };
  }, [previewPhotoUrl]);

  // Transporte
  const [distanceKm, setDistanceKm] = useState<number>(300);
  const [fuelPricePerLiter, setFuelPricePerLiter] = useState<number>(5.89);
  const [fuelEfficiencyKmL, setFuelEfficiencyKmL] = useState<number>(10);
  const isRoundTrip = true;
  const [tollCost, setTollCost] = useState<number>(45);
  const [showTollInfo, setShowTollInfo] = useState<boolean>(false);

  // Aluguel de Carro
  const [carRentalEnabled, setCarRentalEnabled] = useState<boolean>(false);
  const [carRentalPricePerDay, setCarRentalPricePerDay] = useState<number>(DEFAULT_CAR_RENTAL_DAILY_PRICE);
  const [carRentalDaysCount, setCarRentalDaysCount] = useState<number>(5);
  const [hasSundayExtraDay, setHasSundayExtraDay] = useState<boolean>(false);

  // Alimentação
  const [breakfastIncluded, setBreakfastIncluded] = useState<boolean>(false);
  const [mealItems, setMealItems] = useState<ExpenseItem[]>([]);
  const [customExtraItems, setCustomExtraItems] = useState<ExpenseItem[]>([]);
  const [newItemDesc, setNewItemDesc] = useState('');
  const [newItemValue, setNewItemValue] = useState<string>('');

  // UI
  const [isCalculatingRoute, setIsCalculatingRoute] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [notes, setNotes] = useState('');

  // Fechar autocompletes ao clicar fora
  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (originRef.current && !originRef.current.contains(e.target as Node)) {
        setShowOriginAutocomplete(false);
      }
      if (destRef.current && !destRef.current.contains(e.target as Node)) {
        setShowDestAutocomplete(false);
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  // Atualiza refeições automáticas ao mudar datas ou café incluso
  useEffect(() => {
    const generated = generateMealItems(startDate, endDate, breakfastIncluded);
    setMealItems(generated);
  }, [startDate, endDate, breakfastIncluded]);

  // Atualiza carro ao mudar datas
  useEffect(() => {
    const { daysCount, hasSundayExtraDay } = calculateCarRentalDays(startDate, endDate);
    setCarRentalDaysCount(daysCount);
    setHasSundayExtraDay(hasSundayExtraDay);
  }, [startDate, endDate]);

  // Carrega dados para edição
  useEffect(() => {
    if (tripToEdit && isOpen) {
      setTitle(tripToEdit.title || '');
      setOriginAddress(tripToEdit.originAddress || DEFAULT_ORIGIN_ADDRESS);
      setOriginLat(DEFAULT_ORIGIN_COORDS.lat);
      setOriginLng(DEFAULT_ORIGIN_COORDS.lng);

      setDestinationAddress(tripToEdit.destinationAddress || '');
      setDestLat(tripToEdit.destinationLat || -27.5954);
      setDestLng(tripToEdit.destinationLng || -48.5480);
      setStartDate(tripToEdit.startDate || todayStr);
      setEndDate(tripToEdit.endDate || nextWeekStr);
      setAccommodationName(tripToEdit.accommodation?.name || '');
      setPricePerNight(tripToEdit.accommodation?.pricePerNight || 0);
      setAccommodationUrl(tripToEdit.accommodation?.url || '');
      setAccommodationPhotos(tripToEdit.accommodation?.photos || []);
      setCoverImageBase64(tripToEdit.coverImageBase64 || '');
      setDistanceKm(tripToEdit.transport?.distanceKm || 0);
      setFuelPricePerLiter(tripToEdit.transport?.fuelPricePerLiter || 5.89);
      setFuelEfficiencyKmL(tripToEdit.transport?.fuelEfficiencyKmL || 10);
      setTollCost(tripToEdit.transport?.tollCost || 0);
      if (tripToEdit.carRental) {
        setCarRentalEnabled(tripToEdit.carRental.enabled);
        setCarRentalPricePerDay(tripToEdit.carRental.pricePerDay || DEFAULT_CAR_RENTAL_DAILY_PRICE);
        setCarRentalDaysCount(tripToEdit.carRental.daysCount || 5);
        setHasSundayExtraDay(tripToEdit.carRental.hasSundayExtraDay || false);
      }
      setBreakfastIncluded(tripToEdit.breakfastIncluded || false);
      const existing = tripToEdit.extraItems || [];
      setMealItems(existing.filter(i => i.isAutoGenerated && i.mealType));
      setCustomExtraItems(existing.filter(i => !i.isAutoGenerated || !i.mealType));
      setNotes(tripToEdit.notes || '');
    } else if (isOpen && !tripToEdit) {
      resetForm();
    }
  }, [tripToEdit, isOpen]);

  const handleStartDateChange = (newStartDate: string) => {
    setStartDate(newStartDate);
    if (newStartDate) {
      const [sy, sm, sd] = newStartDate.split('-').map(Number);
      const startObj = new Date(sy, sm - 1, sd);
      startObj.setDate(startObj.getDate() + 1);
      
      const year = startObj.getFullYear();
      const month = String(startObj.getMonth() + 1).padStart(2, '0');
      const day = String(startObj.getDate()).padStart(2, '0');
      const nextDayStr = `${year}-${month}-${day}`;

      if (!endDate || endDate <= newStartDate) {
        setEndDate(nextDayStr);
      }
    }
  };

  const resetForm = () => {
    setTitle('');
    setOriginAddress(DEFAULT_ORIGIN_ADDRESS);
    setOriginLat(DEFAULT_ORIGIN_COORDS.lat);
    setOriginLng(DEFAULT_ORIGIN_COORDS.lng);
    setDestinationAddress('');
    setDestLat(-27.5954); setDestLng(-48.5480);
    setRoutePolyline(undefined);
    setStartDate(todayStr); setEndDate(nextWeekStr);
    setAccommodationName(''); setPricePerNight(150);
    setAccommodationUrl(''); setAccommodationPhotos([]); setCoverImageBase64('');
    setDistanceKm(300); setFuelPricePerLiter(5.89); setFuelEfficiencyKmL(10); setTollCost(45);
    setCarRentalEnabled(false); setCarRentalPricePerDay(DEFAULT_CAR_RENTAL_DAILY_PRICE);
    setBreakfastIncluded(false);
    setCustomExtraItems([]);
    setNotes('');
  };

  // Search Origin Autocomplete
  const handleOriginSearch = (query: string) => {
    if (originTimerRef.current) clearTimeout(originTimerRef.current);
    if (!query || query.trim().length < 2) {
      setOriginSuggestions([]);
      setShowOriginAutocomplete(false);
      return;
    }
    originTimerRef.current = setTimeout(async () => {
      const suggestions = await searchPlaceAutocomplete(query);
      setOriginSuggestions(suggestions);
      setShowOriginAutocomplete(suggestions.length > 0);
    }, 250);
  };

  const handleOriginChange = (value: string) => {
    setOriginAddress(value);
    handleOriginSearch(value);
  };

  const handleSelectOrigin = (option: PlaceAutocompleteOption) => {
    const addr = option.display_name_short || option.display_name;
    setOriginAddress(addr);
    setOriginLat(option.lat);
    setOriginLng(option.lng);
    setShowOriginAutocomplete(false);
    autoCalculateRoute(addr, destinationAddress, { lat: option.lat, lng: option.lng }, { lat: destLat, lng: destLng });
  };

  // Search Destination Autocomplete
  const handleDestSearch = (query: string) => {
    if (destTimerRef.current) clearTimeout(destTimerRef.current);
    if (!query || query.trim().length < 2) {
      setDestSuggestions([]);
      setShowDestAutocomplete(false);
      return;
    }
    destTimerRef.current = setTimeout(async () => {
      const suggestions = await searchPlaceAutocomplete(query);
      setDestSuggestions(suggestions);
      setShowDestAutocomplete(suggestions.length > 0);
    }, 250);
  };

  const handleDestChange = (value: string) => {
    setDestinationAddress(value);
    handleDestSearch(value);
  };

  const handleSelectDest = (option: PlaceAutocompleteOption) => {
    const addr = option.display_name_short || option.display_name;
    setDestinationAddress(addr);
    setDestLat(option.lat);
    setDestLng(option.lng);
    setShowDestAutocomplete(false);
    autoCalculateRoute(originAddress, addr, { lat: originLat, lng: originLng }, { lat: option.lat, lng: option.lng });
  };

  const autoCalculateRoute = async (
    origQuery?: string,
    destQuery?: string,
    knownOrig?: { lat: number; lng: number },
    knownDest?: { lat: number; lng: number }
  ) => {
    const oQuery = origQuery !== undefined ? origQuery : originAddress;
    const dQuery = destQuery !== undefined ? destQuery : destinationAddress;
    if (!dQuery.trim()) return;

    setIsCalculatingRoute(true);
    try {
      const routeInfo = await calculateRouteDetails(
        oQuery,
        dQuery,
        fuelPricePerLiter,
        fuelEfficiencyKmL,
        isRoundTrip,
        knownOrig || { lat: originLat, lng: originLng },
        knownDest || { lat: destLat, lng: destLng }
      );

      setDistanceKm(routeInfo.distanceKm);
      setTollCost(routeInfo.estimatedTollCost);
      setOriginLat(routeInfo.originLat);
      setOriginLng(routeInfo.originLng);
      setDestLat(routeInfo.destLat);
      setDestLng(routeInfo.destLng);
      if (routeInfo.routePolyline) setRoutePolyline(routeInfo.routePolyline);
      if (!title) setTitle(`Viagem para ${dQuery.split(',')[0]}`);
    } finally {
      setIsCalculatingRoute(false);
    }
  };

  // Restaurar partida e limpar destino
  const handleRestoreOrigin = () => {
    setOriginAddress(DEFAULT_ORIGIN_ADDRESS);
    setOriginLat(DEFAULT_ORIGIN_COORDS.lat);
    setOriginLng(DEFAULT_ORIGIN_COORDS.lng);
    setDestinationAddress('');
    setDestLat(-27.5954);
    setDestLng(-48.5480);
    setRoutePolyline(undefined);
    setShowOriginAutocomplete(false);
    setShowDestAutocomplete(false);
  };

  // Upload imagem de capa
  const handleCoverImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const base64 = await compressImageToBase64(file, 900);
    setCoverImageBase64(base64);
  };

  // Upload fotos da hospedagem (até 4)
  const handleAccomPhotosUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    if (!files.length) return;
    const remaining = 4 - accommodationPhotos.length;
    const toProcess = files.slice(0, remaining);
    const bases = await Promise.all(toProcess.map(f => compressImageToBase64(f, 700)));
    setAccommodationPhotos(prev => [...prev, ...bases].slice(0, 4));
  };

  // Cálculos
  const nights = calculateNights(startDate, endDate);
  const totalAccommodationCost = Math.round((nights * (pricePerNight || 0)) * 100) / 100;
  const calculatedFuelCost = calculateFuelCost(distanceKm, fuelPricePerLiter, fuelEfficiencyKmL, isRoundTrip);
  const totalCarRentalCost = carRentalEnabled ? (carRentalDaysCount * carRentalPricePerDay) : 0;
  const allExtraItems = [...mealItems, ...customExtraItems];
  const totalExtraItemsCost = allExtraItems.reduce((sum, item) => sum + (item.value || 0), 0);
  const totalEstimateCost = Math.round(
    (totalAccommodationCost + totalCarRentalCost + calculatedFuelCost + (tollCost || 0) + totalExtraItemsCost) * 100
  ) / 100;

  const handleAddExtraItem = () => {
    if (!newItemDesc.trim()) return;
    const val = parseFloat(newItemValue.replace(',', '.')) || 0;
    setCustomExtraItems(prev => [...prev, {
      id: `item_${Date.now()}`,
      description: newItemDesc.trim(),
      value: val
    }]);
    setNewItemDesc(''); setNewItemValue('');
  };

  const handleUpdateMealValue = (id: string, newVal: number) => {
    setMealItems(prev => prev.map(i => i.id === id ? { ...i, value: newVal } : i));
  };

  const handleRemoveMeal = (id: string) => {
    setMealItems(prev => prev.filter(i => i.id !== id));
  };

  const handleRemoveCustom = (id: string) => {
    setCustomExtraItems(prev => prev.filter(i => i.id !== id));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!destinationAddress.trim()) { alert('Informe o destino!'); return; }
    setIsSaving(true);
    try {
      const carRentalInfo: CarRentalInfo = {
        enabled: carRentalEnabled,
        pricePerDay: carRentalPricePerDay,
        daysCount: carRentalDaysCount,
        hasSundayExtraDay,
        totalCost: totalCarRentalCost
      };
      const formData: TripFormData = {
        title: title.trim() || `Viagem para ${destinationAddress}`,
        originAddress,
        originLat,
        originLng,
        destinationAddress,
        destinationLat: destLat,
        destinationLng: destLng,
        startDate, endDate,
        accommodation: {
          name: accommodationName || 'Hospedagem',
          pricePerNight: pricePerNight || 0,
          nightsCount: nights,
          totalCost: totalAccommodationCost,
          url: accommodationUrl,
          photos: accommodationPhotos
        },
        transport: {
          distanceKm: distanceKm || 0,
          isRoundTrip,
          fuelPricePerLiter: fuelPricePerLiter || 0,
          fuelEfficiencyKmL: fuelEfficiencyKmL || 10,
          calculatedFuelCost,
          tollCost: tollCost || 0
        },
        carRental: carRentalInfo,
        extraItems: allExtraItems,
        breakfastIncluded,
        notes,
        coverImageUrl: '',
        coverImageBase64,
        totalEstimateCost,
        status: 'planned'
      };
      await onSave(formData, tripToEdit?.id);
      onClose();
    } catch (err) {
      console.error("Erro ao salvar:", err);
      alert("Erro ao salvar. Verifique a conexão.");
    } finally {
      setIsSaving(false);
    }
  };

  if (!isOpen) return null;

  const sectionStyle = {
    backgroundColor: 'var(--bg-secondary)',
    borderColor: 'var(--border-primary)'
  };
  const inputStyle = {
    backgroundColor: 'var(--bg-input)',
    borderColor: 'var(--border-primary)',
    color: 'var(--text-primary)'
  };
  const labelStyle = { color: 'var(--text-muted)' };

  // Agrupar refeições por dia
  const mealsByDay: Record<number, ExpenseItem[]> = {};
  mealItems.forEach(m => {
    const day = m.mealDay || 0;
    if (!mealsByDay[day]) mealsByDay[day] = [];
    mealsByDay[day].push(m);
  });

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-4 bg-black/70 backdrop-blur-md overflow-y-auto">
      <div
        className="relative w-full max-w-4xl rounded-3xl shadow-2xl overflow-hidden my-4"
        style={{ backgroundColor: 'var(--bg-card)', border: '1px solid var(--border-primary)' }}
      >
        {/* Cabeçalho */}
        <div
          className="flex items-center justify-between p-5 border-b"
          style={{ backgroundColor: 'var(--bg-secondary)', borderColor: 'var(--border-primary)' }}
        >
          <div className="flex items-center space-x-3">
            <div className="p-2.5 rounded-2xl text-white" style={{ background: 'linear-gradient(135deg, var(--accent-dark), var(--accent))' }}>
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold" style={{ color: 'var(--text-primary)' }}>
                {tripToEdit ? 'Editar Viagem' : 'Nova Viagem'}
              </h2>
              <p className="text-xs" style={{ color: 'var(--text-muted)' }}>Preencha os dados e estimativas de custos</p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 rounded-xl border transition-colors cursor-pointer hover:text-white" style={{ backgroundColor: 'var(--bg-input)', borderColor: 'var(--border-primary)', color: 'var(--text-muted)' }}>
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-4 sm:p-6 space-y-5 max-h-[80vh] overflow-y-auto custom-scrollbar">

          {/* IMAGEM DE CAPA */}
          <div className="relative rounded-2xl overflow-hidden h-40 group cursor-pointer border" style={{ borderColor: 'var(--border-primary)' }} onClick={() => coverInputRef.current?.click()}>
            {coverImageBase64 ? (
              <img src={coverImageBase64} alt="Capa" className="w-full h-full object-cover" />
            ) : (
              <div className="w-full h-full flex flex-col items-center justify-center gap-2" style={{ backgroundColor: 'var(--bg-secondary)' }}>
                <Image className="w-8 h-8" style={{ color: 'var(--text-muted)' }} />
                <span className="text-xs" style={{ color: 'var(--text-muted)' }}>Clique para adicionar foto de capa</span>
              </div>
            )}
            <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-2">
              <Upload className="w-5 h-5 text-white" />
              <span className="text-sm font-medium text-white">Trocar Imagem</span>
            </div>
            {coverImageBase64 && (
              <button
                type="button"
                onClick={(e) => { e.stopPropagation(); setCoverImageBase64(''); }}
                className="absolute top-2 right-2 p-1.5 rounded-lg bg-black/60 text-white hover:bg-rose-600 transition-colors cursor-pointer"
              >
                <Trash2 className="w-3.5 h-3.5" />
              </button>
            )}
            <input ref={coverInputRef} type="file" accept="image/*" className="hidden" onChange={handleCoverImageUpload} />
          </div>

          {/* TÍTULO */}
          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider mb-1.5" style={labelStyle}>
              Título da Viagem (Opcional)
            </label>
            <input
              type="text"
              placeholder="Ex: Férias em Florianópolis"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full border rounded-xl px-4 py-2.5 text-sm outline-none transition-colors"
              style={inputStyle}
            />
          </div>

          {/* ORIGEM + DESTINO */}
          <div className="rounded-2xl border p-4 space-y-3" style={sectionStyle}>
            <h4 className="text-xs font-semibold uppercase tracking-wider flex items-center gap-2" style={labelStyle}>
              <Route className="w-4 h-4 text-cyan-400" /> Rota da Viagem
            </h4>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              
              {/* PARTIDA */}
              <div ref={originRef} className="relative">
                <div className="flex items-center justify-between mb-1.5">
                  <label className="text-xs font-semibold uppercase tracking-wider flex items-center gap-1" style={labelStyle}>
                    <Navigation className="w-3.5 h-3.5" style={{ color: 'var(--accent)' }} /> Local de Partida *
                  </label>
                  <button type="button" onClick={handleRestoreOrigin}
                    className="text-[11px] flex items-center gap-1 cursor-pointer hover:underline"
                    style={{ color: 'var(--accent)' }}
                  >
                    <RotateCcw className="w-3 h-3" /> Restaurar Padrão
                  </button>
                </div>
                <input
                  type="text"
                  placeholder="Digite o endereço de partida..."
                  value={originAddress}
                  onChange={(e) => handleOriginChange(e.target.value)}
                  onFocus={() => { if (originAddress.length >= 2) handleOriginSearch(originAddress); }}
                  onClick={() => { if (originAddress.length >= 2) handleOriginSearch(originAddress); }}
                  className="w-full border rounded-xl px-3 py-2.5 text-xs outline-none transition-colors"
                  style={inputStyle}
                  required
                />
                <p className="text-[10px] mt-1 flex items-center gap-1" style={labelStyle}>
                  <Info className="w-3 h-3" style={{ color: 'var(--accent)' }} />
                  Padrão: Rua Alfredo Pucci, 80 — Ribeirão Preto SP
                </p>

                {/* Dropdown Autocomplete Partida */}
                {showOriginAutocomplete && originSuggestions.length > 0 && (
                  <div
                    className="absolute left-0 right-0 top-full mt-1 rounded-2xl border shadow-2xl z-50 max-h-52 overflow-y-auto animate-fadeIn"
                    style={{ backgroundColor: 'var(--bg-card)', borderColor: 'var(--border-secondary)' }}
                  >
                    {originSuggestions.map((item, idx) => (
                      <button
                        key={idx}
                        type="button"
                        onClick={() => handleSelectOrigin(item)}
                        className="w-full text-left px-4 py-3 text-xs flex items-start gap-2 border-b last:border-0 hover:opacity-80 transition-opacity cursor-pointer"
                        style={{ borderColor: 'var(--border-primary)', color: 'var(--text-primary)' }}
                      >
                        <Navigation className="w-3.5 h-3.5 mt-0.5 shrink-0" style={{ color: 'var(--accent)' }} />
                        <div>
                          <span className="font-semibold block">{item.display_name_short}</span>
                          <span className="text-[10px] block mt-0.5" style={{ color: 'var(--text-muted)' }}>{item.display_name}</span>
                        </div>
                      </button>
                    ))}
                  </div>
                )}
              </div>

              {/* DESTINO */}
              <div ref={destRef} className="relative">
                <label className="block text-xs font-semibold uppercase tracking-wider mb-1.5 flex items-center gap-1.5" style={labelStyle}>
                  <MapPin className="w-3.5 h-3.5 text-rose-400" /> Local de Destino *
                </label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    placeholder="Rua, cidade, local de destino..."
                    value={destinationAddress}
                    onChange={(e) => handleDestChange(e.target.value)}
                    onFocus={() => { if (destinationAddress.length >= 2) handleDestSearch(destinationAddress); }}
                    onClick={() => { if (destinationAddress.length >= 2) handleDestSearch(destinationAddress); }}
                    className="flex-1 border rounded-xl px-3 py-2.5 text-sm outline-none transition-colors"
                    style={inputStyle}
                    required
                  />
                  <button
                    type="button"
                    onClick={() => autoCalculateRoute()}
                    disabled={isCalculatingRoute}
                    className="px-3.5 rounded-xl text-xs font-semibold text-white cursor-pointer flex items-center gap-1.5 shrink-0 transition-transform active:scale-95"
                    style={{ background: 'linear-gradient(135deg, var(--accent-dark), var(--accent))' }}
                  >
                    {isCalculatingRoute ? <span className="animate-spin">⟳</span> : <Calculator className="w-4 h-4" />}
                    <span className="hidden sm:inline">Calcular</span>
                  </button>
                </div>

                {/* Dropdown Autocomplete Destino */}
                {showDestAutocomplete && destSuggestions.length > 0 && (
                  <div
                    className="absolute left-0 right-0 top-full mt-1 rounded-2xl border shadow-2xl z-50 max-h-52 overflow-y-auto animate-fadeIn"
                    style={{ backgroundColor: 'var(--bg-card)', borderColor: 'var(--border-secondary)' }}
                  >
                    {destSuggestions.map((item, idx) => (
                      <button
                        key={idx}
                        type="button"
                        onClick={() => handleSelectDest(item)}
                        className="w-full text-left px-4 py-3 text-xs flex items-start gap-2 border-b last:border-0 hover:opacity-80 transition-opacity cursor-pointer"
                        style={{ borderColor: 'var(--border-primary)', color: 'var(--text-primary)' }}
                      >
                        <MapPin className="w-3.5 h-3.5 mt-0.5 shrink-0" style={{ color: 'var(--accent)' }} />
                        <div>
                          <span className="font-semibold block">{item.display_name_short}</span>
                          <span className="text-[10px] block mt-0.5" style={{ color: 'var(--text-muted)' }}>{item.display_name}</span>
                        </div>
                      </button>
                    ))}
                  </div>
                )}
              </div>

            </div>
          </div>

          {/* MAPA */}
          {destinationAddress.trim().length > 0 && (
            <MapRoute
              destinationName={destinationAddress}
              originLat={originLat}
              originLng={originLng}
              destLat={destLat}
              destLng={destLng}
              routePolyline={routePolyline}
            />
          )}

          {/* DATAS */}
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 rounded-2xl border p-4" style={sectionStyle}>
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider mb-1.5 flex items-center gap-1" style={labelStyle}>
                <Calendar className="w-3.5 h-3.5" style={{ color: 'var(--accent)' }} /> Data de Ida
              </label>
              <input
                type="date"
                value={startDate}
                onChange={(e) => handleStartDateChange(e.target.value)}
                className="w-full border rounded-xl px-3 py-2 text-sm outline-none cursor-pointer"
                style={inputStyle}
                required
              />
            </div>
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider mb-1.5 flex items-center gap-1" style={labelStyle}>
                <Calendar className="w-3.5 h-3.5" style={{ color: 'var(--accent)' }} /> Data de Volta
              </label>
              <input
                type="date"
                value={endDate}
                min={startDate}
                onChange={(e) => setEndDate(e.target.value)}
                className="w-full border rounded-xl px-3 py-2 text-sm outline-none cursor-pointer"
                style={inputStyle}
                required
              />
            </div>
            <div className="flex flex-col items-center justify-center rounded-xl border p-2" style={{ backgroundColor: 'var(--bg-input)', borderColor: 'var(--border-primary)' }}>
              <span className="text-[10px] uppercase font-semibold" style={labelStyle}>Total</span>
              <span className="text-xl font-extrabold" style={{ color: 'var(--accent)' }}>{nights} {nights === 1 ? 'Noite' : 'Noites'}</span>
            </div>
          </div>

          {/* HOSPEDAGEM */}
          <div className="rounded-2xl border p-4 space-y-4" style={sectionStyle}>
            <h4 className="text-xs font-semibold uppercase tracking-wider flex items-center gap-2" style={labelStyle}>
              <Hotel className="w-4 h-4 text-indigo-400" /> Hospedagem
            </h4>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div className="sm:col-span-2">
                <label className="block text-xs mb-1" style={labelStyle}>Local de Hospedagem</label>
                <input type="text" placeholder="Ex: Pousada Beira Mar, Airbnb, Hotel..."
                  value={accommodationName} onChange={(e) => setAccommodationName(e.target.value)}
                  className="w-full border rounded-xl px-3.5 py-2 text-sm outline-none" style={inputStyle} />
              </div>
              <div>
                <label className="block text-xs mb-1" style={labelStyle}>Preço por Diária (R$)</label>
                <input type="number" step="0.01" min="0" value={pricePerNight}
                  onChange={(e) => setPricePerNight(parseFloat(e.target.value) || 0)}
                  className="w-full border rounded-xl px-3.5 py-2 text-sm outline-none" style={inputStyle} />
              </div>
            </div>

            {/* URL da Hospedagem */}
            <div>
              <label className="block text-xs mb-1 flex items-center gap-1" style={labelStyle}>
                <Link className="w-3.5 h-3.5" /> Link da Hospedagem (Airbnb, Booking, etc.)
              </label>
              <input type="url" placeholder="https://www.airbnb.com.br/rooms/..."
                value={accommodationUrl} onChange={(e) => setAccommodationUrl(e.target.value)}
                className="w-full border rounded-xl px-3.5 py-2 text-sm outline-none" style={inputStyle} />
              {accommodationUrl && (
                <a href={accommodationUrl} target="_blank" rel="noopener noreferrer"
                  className="text-[11px] mt-1 flex items-center gap-1 hover:underline" style={{ color: 'var(--accent)' }}>
                  <Link className="w-3 h-3" /> Abrir link da hospedagem ↗
                </a>
              )}
            </div>

            {/* Fotos da Hospedagem */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="text-xs font-semibold flex items-center gap-1" style={labelStyle}>
                  <Image className="w-3.5 h-3.5" /> Fotos da Hospedagem ({accommodationPhotos.length}/4)
                </label>
                {accommodationPhotos.length < 4 && (
                  <button type="button" onClick={() => accomPhotosInputRef.current?.click()}
                    className="text-[11px] flex items-center gap-1 px-2.5 py-1 rounded-lg border cursor-pointer"
                    style={{ borderColor: 'var(--border-secondary)', color: 'var(--accent)' }}>
                    <Upload className="w-3 h-3" /> Adicionar Fotos
                  </button>
                )}
                <input ref={accomPhotosInputRef} type="file" accept="image/*" multiple className="hidden" onChange={handleAccomPhotosUpload} />
              </div>

              {accommodationPhotos.length > 0 && (
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                  {accommodationPhotos.map((photo, idx) => (
                    <div
                      key={idx}
                      className="relative rounded-xl overflow-hidden h-24 group cursor-pointer border hover:scale-[1.02] transition-all"
                      style={{ borderColor: 'var(--border-primary)' }}
                      onClick={() => setPreviewPhotoUrl(photo)}
                      title="Clique para ampliar esta foto"
                    >
                      <img src={photo} alt={`Hospedagem ${idx + 1}`} className="w-full h-full object-cover group-hover:opacity-90 transition-opacity" />
                      <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center text-white text-[10px] font-bold">
                        🔍 Ampliar
                      </div>
                      <button
                        type="button"
                        onClick={(e) => { e.stopPropagation(); setAccommodationPhotos(prev => prev.filter((_, i) => i !== idx)); }}
                        className="absolute top-1.5 right-1.5 p-1 rounded-lg bg-black/70 text-white opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer hover:bg-rose-600 border border-white/20"
                        title="Remover foto"
                      >
                        <Trash2 className="w-3 h-3" />
                      </button>
                    </div>
                  ))}
                  {accommodationPhotos.length < 4 && (
                    <div
                      className="rounded-xl h-24 flex items-center justify-center cursor-pointer border-2 border-dashed"
                      style={{ borderColor: 'var(--border-secondary)' }}
                      onClick={() => accomPhotosInputRef.current?.click()}
                    >
                      <Plus className="w-6 h-6" style={{ color: 'var(--text-muted)' }} />
                    </div>
                  )}
                </div>
              )}
            </div>

            <div
              className="flex justify-between items-center text-xs px-3 py-2 rounded-xl border"
              style={{ backgroundColor: 'var(--bg-input)', borderColor: 'var(--border-primary)' }}
            >
              <span style={{ color: 'var(--text-muted)' }}>Total Hospedagem ({nights}x {formatCurrency(pricePerNight)}):</span>
              <span className="font-bold text-indigo-400 text-sm">{formatCurrency(totalAccommodationCost)}</span>
            </div>
          </div>

          {/* TRANSPORTE */}
          <div className="rounded-2xl border p-4 space-y-4" style={sectionStyle}>
            <h4 className="text-xs font-semibold uppercase tracking-wider flex items-center gap-2" style={labelStyle}>
              <Fuel className="w-4 h-4 text-amber-400" /> Transporte, Combustível & Pedágios (Ida + Volta)
            </h4>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              <div>
                <label className="block text-xs mb-1" style={labelStyle}>Distância Ida (km)</label>
                <input type="number" min="1" value={distanceKm}
                  onChange={(e) => { const d = parseFloat(e.target.value) || 0; setDistanceKm(d); setTollCost(estimateTollCost(d, isRoundTrip)); }}
                  className="w-full border rounded-xl px-3 py-2 text-sm outline-none font-semibold" style={inputStyle} />
                <span className="text-[10px] mt-0.5 block" style={labelStyle}>Total: {distanceKm * 2} km</span>
              </div>
              <div>
                <label className="block text-xs mb-1" style={labelStyle}>Combustível (R$/L)</label>
                <input type="number" step="0.01" min="0" value={fuelPricePerLiter}
                  onChange={(e) => setFuelPricePerLiter(parseFloat(e.target.value) || 0)}
                  className="w-full border rounded-xl px-3 py-2 text-sm outline-none" style={inputStyle} />
              </div>
              <div>
                <label className="block text-xs mb-1" style={labelStyle}>Consumo (km/L)</label>
                <input type="number" step="0.1" min="1" value={fuelEfficiencyKmL}
                  onChange={(e) => setFuelEfficiencyKmL(parseFloat(e.target.value) || 10)}
                  className="w-full border rounded-xl px-3 py-2 text-sm outline-none" style={inputStyle} />
              </div>
              <div>
                <div className="flex items-center gap-1 mb-1">
                  <label className="text-xs" style={labelStyle}>Pedágios (R$)</label>
                  <div className="relative group cursor-pointer">
                    <button
                      type="button"
                      onClick={() => setShowTollInfo(!showTollInfo)}
                      className="text-cyan-400 hover:text-cyan-300 transition-colors cursor-pointer flex items-center justify-center p-0.5"
                      title="Como esse valor foi calculado?"
                    >
                      <HelpCircle className="w-3.5 h-3.5" />
                    </button>
                    
                    {/* Tooltip / Popover Explicativo */}
                    <div className={`absolute right-0 sm:left-1/2 sm:-translate-x-1/2 bottom-full mb-2 ${showTollInfo ? 'block' : 'hidden group-hover:block'} w-64 p-3 rounded-2xl border shadow-2xl z-50 text-[11px] leading-snug animate-fadeIn`}
                      style={{ backgroundColor: 'var(--bg-card)', borderColor: 'var(--border-secondary)', color: 'var(--text-primary)' }}
                    >
                      <div className="font-bold text-cyan-400 mb-1 flex items-center gap-1">
                        <HelpCircle className="w-3.5 h-3.5 shrink-0" /> Origem do Valor dos Pedágios
                      </div>
                      <p className="text-[10px] leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
                        Valor calculado automaticamente para <strong>Ida e Volta ({distanceKm * 2} km total)</strong> com base nas tarifas médias oficiais das praças de pedágio rodoviárias (ANTT/ARTESP) estimadas para esta rota.
                      </p>
                      <span className="block mt-1.5 text-[9px] italic" style={{ color: 'var(--text-muted)' }}>
                        💡 Você pode alterar ou zerar este valor manualmente.
                      </span>
                    </div>
                  </div>
                </div>
                <input type="number" step="0.01" min="0" value={tollCost}
                  onChange={(e) => setTollCost(parseFloat(e.target.value) || 0)}
                  className="w-full border rounded-xl px-3 py-2 text-sm outline-none font-semibold" style={inputStyle} />
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
              <div className="flex items-center justify-between px-3 py-2 rounded-xl border" style={{ backgroundColor: 'var(--bg-input)', borderColor: 'var(--border-primary)' }}>
                <span style={labelStyle}>Combustível (Ida e Volta):</span>
                <span className="font-bold text-amber-400">{formatCurrency(calculatedFuelCost)}</span>
              </div>
              <div className="flex items-center justify-between px-3 py-2 rounded-xl border" style={{ backgroundColor: 'var(--bg-input)', borderColor: 'var(--border-primary)' }}>
                <span style={labelStyle}>Pedágios (Ida e Volta):</span>
                <span className="font-bold" style={{ color: 'var(--accent)' }}>{formatCurrency(tollCost)}</span>
              </div>
            </div>
          </div>

          {/* ALUGUEL DE CARRO */}
          <div className="rounded-2xl border p-4 space-y-3" style={sectionStyle}>
            <div className="flex items-center justify-between">
              <h4 className="text-xs font-semibold uppercase tracking-wider flex items-center gap-2" style={labelStyle}>
                <Car className="w-4 h-4 text-blue-400" /> Aluguel de Veículo
              </h4>
              <div className="flex bg-black/20 p-0.5 rounded-xl border" style={{ borderColor: 'var(--border-primary)' }}>
                <button type="button" onClick={() => setCarRentalEnabled(true)}
                  className="px-3 py-1 rounded-lg text-xs font-semibold transition-colors cursor-pointer"
                  style={carRentalEnabled ? { backgroundColor: 'var(--accent)', color: 'white' } : { color: 'var(--text-muted)' }}>
                  Sim
                </button>
                <button type="button" onClick={() => setCarRentalEnabled(false)}
                  className="px-3 py-1 rounded-lg text-xs font-semibold transition-colors cursor-pointer"
                  style={!carRentalEnabled ? { backgroundColor: 'var(--bg-card)', color: 'var(--text-primary)' } : { color: 'var(--text-muted)' }}>
                  Não
                </button>
              </div>
            </div>

            {carRentalEnabled && (
              <div className="rounded-2xl border p-4 space-y-3 animate-fadeIn" style={{ backgroundColor: 'var(--bg-input)', borderColor: '#1d4ed850' }}>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                  <div>
                    <label className="block text-xs mb-1" style={labelStyle}>Diária do Carro (R$)</label>
                    <input type="number" step="0.01" min="0" value={carRentalPricePerDay}
                      onChange={(e) => setCarRentalPricePerDay(parseFloat(e.target.value) || 0)}
                      className="w-full border rounded-xl px-3 py-2 text-sm outline-none font-semibold" style={inputStyle} />
                    <span className="text-[10px] mt-0.5 block" style={labelStyle}>Média: R$ 120,00/dia</span>
                  </div>
                  <div>
                    <label className="block text-xs mb-1" style={labelStyle}>Quantidade de Diárias</label>
                    <input type="number" min="1" value={carRentalDaysCount}
                      onChange={(e) => setCarRentalDaysCount(parseInt(e.target.value) || 1)}
                      className="w-full border rounded-xl px-3 py-2 text-sm outline-none font-semibold" style={inputStyle} />
                  </div>
                  <div className="flex flex-col items-center justify-center rounded-xl border p-3" style={{ backgroundColor: 'var(--bg-card)', borderColor: 'var(--border-primary)' }}>
                    <span className="text-[10px] uppercase font-semibold" style={labelStyle}>Total Locação</span>
                    <span className="text-lg font-extrabold text-blue-400">{formatCurrency(totalCarRentalCost)}</span>
                  </div>
                </div>
                {hasSundayExtraDay && (
                  <div className="p-2.5 rounded-xl border text-[11px] text-blue-300 flex items-center gap-2" style={{ backgroundColor: '#1e3a5f50', borderColor: '#1d4ed870' }}>
                    <AlertCircle className="w-4 h-4 text-blue-400 shrink-0" />
                    <span><strong>Regra do Domingo:</strong> A viagem inicia ou termina em domingo — +1 diária adicionada automaticamente.</span>
                  </div>
                )}
              </div>
            )}
          </div>

          {/* ALIMENTAÇÃO POR DIA */}
          <div className="rounded-2xl border p-4 space-y-4" style={sectionStyle}>
            <div className="flex flex-wrap items-center justify-between gap-3">
              <h4 className="text-xs font-semibold uppercase tracking-wider flex items-center gap-2" style={labelStyle}>
                <Ticket className="w-4 h-4 text-emerald-400" /> Alimentação & Itens Extras
              </h4>

              {/* Café Incluso Toggle */}
              <div
                className="flex items-center gap-2 px-3 py-1.5 rounded-xl border cursor-pointer select-none"
                style={{ backgroundColor: 'var(--bg-input)', borderColor: 'var(--border-primary)' }}
                onClick={() => setBreakfastIncluded(prev => !prev)}
              >
                <div
                  className="w-8 h-4 rounded-full border transition-colors relative"
                  style={{
                    backgroundColor: breakfastIncluded ? 'var(--accent)' : 'var(--bg-secondary)',
                    borderColor: breakfastIncluded ? 'var(--accent)' : 'var(--border-secondary)'
                  }}
                >
                  <div
                    className="absolute top-0.5 w-3 h-3 rounded-full bg-white transition-transform"
                    style={{ transform: breakfastIncluded ? 'translateX(16px)' : 'translateX(2px)' }}
                  />
                </div>
                <Coffee className="w-3.5 h-3.5 text-amber-400" />
                <span className="text-xs font-medium" style={{ color: 'var(--text-secondary)' }}>
                  Café incluso na hospedagem
                </span>
              </div>
            </div>

            {/* Refeições por Dia */}
            <div className="space-y-3 max-h-72 overflow-y-auto pr-1 custom-scrollbar">
              {Object.entries(mealsByDay).sort(([a], [b]) => Number(a) - Number(b)).map(([day, meals]) => (
                <div key={day} className="rounded-xl border overflow-hidden" style={{ borderColor: 'var(--border-primary)' }}>
                  <div
                    className="px-3 py-1.5 text-[11px] font-semibold uppercase tracking-wider"
                    style={{ backgroundColor: 'var(--bg-input)', color: 'var(--text-muted)' }}
                  >
                    Dia {day}
                  </div>
                  {meals.map(meal => (
                    <div
                      key={meal.id}
                      className="flex items-center justify-between px-3 py-2 border-t text-xs"
                      style={{ borderColor: 'var(--border-primary)' }}
                    >
                      <span style={{ color: 'var(--text-primary)' }}>{meal.description}</span>
                      <div className="flex items-center gap-2">
                        <span className="text-[10px] mr-1" style={{ color: 'var(--text-muted)' }}>R$</span>
                        <input
                          type="number"
                          step="0.01"
                          min="0"
                          value={meal.value}
                          onChange={(e) => handleUpdateMealValue(meal.id, parseFloat(e.target.value) || 0)}
                          className="w-20 border rounded-lg px-2 py-1 text-xs text-right outline-none"
                          style={inputStyle}
                        />
                        <button type="button" onClick={() => handleRemoveMeal(meal.id)}
                          className="text-rose-400 hover:text-rose-300 transition-colors cursor-pointer">
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              ))}
            </div>

            {/* Itens Extras Customizados */}
            {customExtraItems.length > 0 && (
              <div className="space-y-1.5">
                <span className="text-[11px] font-semibold uppercase" style={labelStyle}>Itens Adicionais</span>
                {customExtraItems.map(item => (
                  <div key={item.id}
                    className="flex items-center justify-between p-2.5 rounded-xl border text-xs"
                    style={{ backgroundColor: 'var(--bg-input)', borderColor: 'var(--border-primary)' }}
                  >
                    <span style={{ color: 'var(--text-primary)' }}>{item.description}</span>
                    <div className="flex items-center gap-3">
                      <span className="font-semibold text-emerald-400">{formatCurrency(item.value)}</span>
                      <button type="button" onClick={() => handleRemoveCustom(item.id)}
                        className="text-rose-400 hover:text-rose-300 cursor-pointer">
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Adicionar Item Extra */}
            <div className="flex flex-col sm:flex-row gap-2">
              <input type="text" placeholder="Ex: Ingresso, Passeio, Compras..."
                value={newItemDesc} onChange={(e) => setNewItemDesc(e.target.value)}
                className="flex-1 border rounded-xl px-3.5 py-2 text-xs outline-none" style={inputStyle} />
              <input type="number" step="0.01" placeholder="Valor R$"
                value={newItemValue} onChange={(e) => setNewItemValue(e.target.value)}
                className="w-full sm:w-28 border rounded-xl px-3.5 py-2 text-xs outline-none" style={inputStyle} />
              <button type="button" onClick={handleAddExtraItem}
                className="px-4 py-2 text-white font-semibold rounded-xl text-xs flex items-center justify-center gap-1 transition-colors cursor-pointer"
                style={{ backgroundColor: '#059669' }}>
                <Plus className="w-4 h-4" /> Adicionar
              </button>
            </div>
          </div>

          {/* NOTAS */}
          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider mb-1.5" style={labelStyle}>
              Observações (Opcional)
            </label>
            <textarea
              placeholder="Dicas, lembretes, itens a levar..."
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={3}
              className="w-full border rounded-xl px-4 py-2.5 text-sm outline-none resize-none"
              style={inputStyle}
            />
          </div>

          {/* RESUMO FINAL */}
          <div
            className="p-4 rounded-2xl border flex flex-col sm:flex-row items-center justify-between gap-4"
            style={{ background: 'linear-gradient(135deg, var(--bg-secondary), var(--bg-card))', borderColor: 'var(--accent-border)' }}
          >
            <div>
              <span className="text-xs uppercase font-semibold block" style={labelStyle}>Estimativa Total</span>
              <span className="text-2xl font-black text-emerald-500">{formatCurrency(totalEstimateCost)}</span>
            </div>
            <div className="flex items-center gap-3 w-full sm:w-auto">
              <button type="button" onClick={onClose}
                className="flex-1 sm:flex-none px-4 py-2.5 rounded-xl text-xs font-semibold border cursor-pointer"
                style={{ borderColor: 'var(--border-secondary)', color: 'var(--text-secondary)' }}>
                Cancelar
              </button>
              <button type="submit" disabled={isSaving}
                className="flex-1 sm:flex-none px-6 py-2.5 rounded-xl text-xs font-bold text-white cursor-pointer flex items-center justify-center gap-2"
                style={{ background: 'linear-gradient(135deg, var(--accent-dark), var(--accent))', boxShadow: '0 4px 14px var(--shadow-accent)' }}>
                {isSaving ? 'Salvando...' : tripToEdit ? 'Salvar Alterações' : 'Criar Viagem ✈️'}
              </button>
            </div>
          </div>

        </form>
      </div>

      {/* Modal Lightbox para Ampliação de Fotos da Hospedagem */}
      {previewPhotoUrl && (
        <div
          className="fixed inset-0 z-[65] flex items-center justify-center bg-black/92 backdrop-blur-md p-4 animate-fadeIn"
          onClick={() => setPreviewPhotoUrl(null)}
        >
          <div className="relative max-w-4xl w-full flex flex-col items-center justify-center" onClick={e => e.stopPropagation()}>
            <img
              src={previewPhotoUrl}
              alt="Foto da Hospedagem Ampliada"
              className="w-full max-h-[85vh] object-contain rounded-2xl shadow-2xl border border-white/10"
            />
            <button
              type="button"
              onClick={() => setPreviewPhotoUrl(null)}
              className="absolute top-3 right-3 p-2.5 rounded-full bg-black/80 text-white cursor-pointer hover:bg-black hover:scale-110 transition-all border border-white/20 shadow-xl"
              title="Fechar (Esc)"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
